
<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Wellington Leonardo</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="/">Home</a></li>
            
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">TURMAS<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="/opMicro">Operador de Micro</a></li>
                      <li><a href="/montagem">Montagem e Manutençao</a></li>
                      <li><a href="/web">Desenvolvedor Web</a></li>
                  </ul>
              </li>
            <li><a href="#contact">MATERIAIS</a></li>
            <li><a href="#contact">SOBRE</a></li>
            <li><a href="">Painel</a></li>

          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>