<?=$this->render('bootstrap/header',$data);?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="alunos">
                <div class="panel panel-primary">
                    <div class="panel-heading"><?=$data->titulo?></div>
                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tbody>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th> Nome</th>
                                        <th>Data de Nascimento</th>
                                        <th>Telefone</th>
                                    </tr>
                                </thead>

                                <?php foreach($data->all() as $obj): ?>
                                    <tr>
                                        <td><?=$obj->id?></td>
                                        <td><?=$obj->nomeAluno?></td>
                                        <td><?=$obj->dnAluno?></td>
                                        <td><?=$obj->telefoneAluno?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <p><?=$data->message?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?=$this->render('bootstrap/header',$data);?>

<table class="table table-bordered">
    ...
</table>
