<?=$this->render('bootstrap/header',$data);?>
<?=$this->render('bootstrap/menu',$data);?>
   <style>
       a{
           color: #175E99;
       }

   </style>
<section class="container" >
    <div class="row">
        <div class="col-sm-12">
            <header>
                <h2><span class="glyphicon glyphicon-education" aria-hidden="true"></span> Cronograma do curso de operador de Microcomputador</h2>
                <span>...</span>
            </header>
        </div>
    </div>
    <div class="container" >
        <div class="row">
            <div class="col-md-12">

                    <div class="panel panel-primary" style="background-color:#DFF0D8; padding: 5px">

                            <h1 style="text-align: center; color: #175E99; font-family: Cedarville Cursive">Windows</h1>

                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" style="color: #568A56">
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingOne">
                                        <h4 class="panel-title">
                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                                Aula 1 - Introdução ao Processamento de Dados / Introdução ao Curso.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Introdução ao curso
                                                </li>
                                                <li>
                                                    Introdução ao Processamento de dados
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingTwo">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                Aula 2 - Introdução ao Sistema Operacional Windows
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Conhecendo o Windows.
                                                </li>
                                                <li>
                                                    Ambiente de trabalho.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingThree">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                Aula 3 - Barra de Tarefas e Menu Iniciar
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Barra de tarefas.
                                                </li>
                                                <li>
                                                    Menu Iniciar.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingFor">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFor" aria-expanded="false" aria-controls="collapseFor">
                                                Aula 4 - Conhecendo o Teclado e Editores de Texto.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseFor" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFor">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Usando o teclado.
                                                </li>
                                                <li>
                                                    Notas Autoadesivas.
                                                </li>
                                                <li>
                                                    Bloco de Notas.
                                                </li>
                                                <li>
                                                    WordPad.
                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingFive">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                                Aula 5 -Calculadora, Paint e Ferramenta de Captura.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Usando o teclado.
                                                </li>
                                                <li>
                                                    Calculadora.
                                                </li>
                                                <li>
                                                    Paint.
                                                </li>
                                                <li>
                                                    Ferramenta de Captura.
                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingSix">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                                Aula 6 - Continuação do Exercício da Aula 5.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Desenhos no Paint.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>


                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingSeven">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                                                Aula 7 - Pastas e Arquivos.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Trabalhando com arquivos e pastas.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingEight">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                                                Aula 8 - Exercícios de Fixação.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Exercitando  com arquivos e pastas.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingNine">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                                                Aula 9 - Armazenamento.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingNine">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Unidades de Medidas.
                                                </li>
                                                <li>
                                                    Dispositivos de Armazenamento.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingTen">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
                                                Aula 10 - Janelas.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTen">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Trabalhando com janelas
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingEleven">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
                                                Aula 11 - Arquivos.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEleven">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Manipulação de Arquivos.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>


                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingTwelve">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve" aria-expanded="false" aria-controls="collapseTwelve">
                                                Aula 12 - Painel de controle / Contas de usuário.
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwelve">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Contas de usuário.
                                                </li>
                                                <li>
                                                    Sistema.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingThirteen">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThirteen" aria-expanded="false" aria-controls="collapseThirteen">
                                                Aula 13 - Tipos de Arquivos
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThirteen">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Formatos de Arquivos e Programas para abri-los.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingFourteen">
                                        <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFourteen" aria-expanded="false" aria-controls="collapseFourteen">
                                                Aula 14 - Prova
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFourteen">
                                        <div class="panel-body">
                                            <ul>
                                                <li>
                                                    Teste de Conhecimento.
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                            </div><!--final do modulo de windos-->



                        <!--Final do modulo de internet  -->
                    </div>
            </div>
        </div>
    </div>
</section>

<?=$this->render('bootstrap/footer',$data);?>