

<?=$this->render('bootstrap/header',$data);?>
<?=$this->render('bootstrap/menu',$data);?>
    <style>
        a{
            color: #175E99;

        }
        a:hover{
            text-decoration: no-underline;
        }
        .panel-heading:hover{

            color: #F5F5F5;

            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#20B2AA),  color-stop(25%,#008B8B), color-stop(50%,#008B8B), color-stop(100%,#175E99));;


        }
        .panel-heading:target {
            color: #ffffff;
            background-color: #175E99;
        }
    </style>
    <div class="panel-heading"><?=$data->titulo?></div>
    <section class="container" >
        <div class="row">
            <div class="col-sm-12">
                <header>
                    <h2><span class="glyphicon glyphicon-education" aria-hidden="true"></span> Cronograma do curso de Desenvolvedor Web</h2>
                    <span>...</span>
                </header>
                <div class="panel panel-primary" style="background-color:#DFF0D8; padding: 5px">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" style="color: #568A56">

                        <h1 style="text-align: center; color: #175E99; font-family: Cedarville Cursive">Windows</h1><!----inicio windows--->

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab"  href="u" id="headingOne">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        Aula 1 - Introdução ao Processamento de Dados / Introdução ao Curso.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Introdução ao curso
                                        </li>
                                        <li>
                                            Introdução ao Processamento de dados
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" href="o" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Aula 2 - Introdução ao Sistema Operacional Windows
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Conhecendo o Windows.
                                        </li>
                                        <li>
                                            Ambiente de trabalho.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThree">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                        Aula 3 - Barra de Tarefas e Menu Iniciar
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Barra de tarefas.
                                        </li>
                                        <li>
                                            Menu Iniciar.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFor">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFor" aria-expanded="false" aria-controls="collapseFor">
                                        Aula 4 - Conhecendo o Teclado e Editores de Texto.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFor" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFor">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Usando o teclado.
                                        </li>
                                        <li>
                                            Notas Autoadesivas.
                                        </li>
                                        <li>
                                            Bloco de Notas.
                                        </li>
                                        <li>
                                            WordPad.
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFive">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                        Aula 5 -Calculadora, Paint e Ferramenta de Captura.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Usando o teclado.
                                        </li>
                                        <li>
                                            Calculadora.
                                        </li>
                                        <li>
                                            Paint.
                                        </li>
                                        <li>
                                            Ferramenta de Captura.
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSix">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                        Aula 6 - Continuação do Exercício da Aula 5.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Desenhos no Paint.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSeven">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                                        Aula 7 - Pastas e Arquivos.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Trabalhando com arquivos e pastas.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingEight">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                                        Aula 8 - Exercícios de Fixação.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Exercitando  com arquivos e pastas.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingNine">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                                        Aula 9 - Armazenamento.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingNine">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Unidades de Medidas.
                                        </li>
                                        <li>
                                            Dispositivos de Armazenamento.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
                                        Aula 10 - Janelas.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Trabalhando com janelas
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingEleven">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
                                        Aula 11 - Arquivos.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEleven">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Manipulação de Arquivos.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwelve">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve" aria-expanded="false" aria-controls="collapseTwelve">
                                        Aula 12 - Painel de controle / Contas de usuário.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwelve">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Contas de usuário.
                                        </li>
                                        <li>
                                            Sistema.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThirteen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThirteen" aria-expanded="false" aria-controls="collapseThirteen">
                                        Aula 13 - Tipos de Arquivos
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThirteen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Formatos de Arquivos e Programas para abri-los.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFourteen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFourteen" aria-expanded="false" aria-controls="collapseFourteen">
                                        Aula 14 - Prova
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFourteen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Teste de Conhecimento.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--final do modulo de windos-->

                        <h1 style="text-align: center; color: #175E99; font-family: Cedarville Cursive">INTERNET</h1>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOneI">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOneI" aria-expanded="false" aria-controls="collapseOneI">
                                        Aula 1 - Introdução à Internet.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOneI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOneI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Historia da Internet
                                        </li>
                                        <li>
                                            Definição de Rede de Computador.
                                        </li>
                                        <li>
                                            Tipos de conexão, Browsers e Dispositivos para acessar a Internet.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwoI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwoI" aria-expanded="false" aria-controls="collapseTwoI">
                                        Aula 2 - URL e Navegadores
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwoI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwoI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Formatos de endereços na internet
                                        </li>
                                        <li>
                                            Definindo e Configurando Navegadores.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThreeI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThreeI" aria-expanded="false" aria-controls="collapseThreeI">
                                        Aula 3 - Pesquisas
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThreeI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThreeI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Sites específicos para pesquisa.
                                        </li>
                                        <li>
                                            Sites específicos para pesquisa.
                                        </li>
                                        <li>
                                            Baixar(Texto, Imagem, Video).
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingForI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForI" aria-expanded="false" aria-controls="collapseForI">
                                        Aula 4 - Tipos de Extensão, Spywares, Vírus, e outros Malwares e Antivírus.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseForI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingForI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Extensões.
                                        </li>
                                        <li>
                                            Malwares.
                                        </li>
                                        <li>
                                            Antivírus.
                                        </li>

                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFiveI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFiveI" aria-expanded="false" aria-controls="collapseFiveI">
                                        Aula 5 - Cuidados ao Navegar.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFiveI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFiveI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Sites e links suspeitos.
                                        </li>
                                        <li>
                                            Fraudes bancárias.
                                        </li>
                                        <li>
                                            Bloquear e desbloquear popup.
                                        </li>
                                        <li>
                                            Hacker e cracker.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSixI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSixI" aria-expanded="false" aria-controls="collapseSixI">
                                        Aula 6 - E-mail.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSixI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSixI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Definição de E-Mail.
                                        </li>
                                        <li>
                                            Opções de Provedores.
                                        </li>
                                        <li>
                                            Criação de Conta.
                                        </li>
                                        <li>
                                            Envio de e-mail
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSevenI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSevenI" aria-expanded="false" aria-controls="collapseSevenI">
                                        Aula 7 - Exercícios com envio de mensagens eletrônicas
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSevenI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSevenI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Assunto, Mensagem e Anexo.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingEightI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEightI" aria-expanded="false" aria-controls="collapseEightI">
                                        Aula 8 - Redes Sociais.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseEightI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEightI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Entreternimento
                                        </li>
                                        <li>
                                            Uso para fins Profissional
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingNineI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNineI" aria-expanded="false" aria-controls="collapseNineI">
                                        Aula 9 - Download.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseNineI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingNineI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Download de Programas.
                                        </li>

                                        <li>
                                            Download de Músicas.
                                        </li>
                                        <li>
                                            Download de Vídeos.
                                        </li>
                                        <li>
                                            Download Via Torrent.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTenI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTenI" aria-expanded="false" aria-controls="collapseTenI">
                                        Aula 9 - Armazenamento de Arquivos na Nuvem.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTenI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTenI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Google Drive.
                                        </li>

                                        <li>
                                            Dropbox.
                                        </li>
                                        <li>
                                            OneDrive.
                                        </li>
                                        <li>
                                            Mega.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTenI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTenI" aria-expanded="false" aria-controls="collapseTenI">
                                        Aula 9 - Armazenamento de Arquivos na Nuvem.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTenI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTenI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Google Drive.
                                        </li>

                                        <li>
                                            Dropbox.
                                        </li>
                                        <li>
                                            OneDrive.
                                        </li>
                                        <li>
                                            Mega.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTenI">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTenI" aria-expanded="false" aria-controls="collapseTenI">
                                        Aula 9 - Armazenamento de Arquivos na Nuvem.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTenI" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTenI">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Google Drive.
                                        </li>

                                        <li>
                                            Dropbox.
                                        </li>
                                        <li>
                                            OneDrive.
                                        </li>
                                        <li>
                                            Mega.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!----------Final Módulo de Internet-------------------------->

                        <h1 style="text-align: center; color: #175E99; font-family: Cedarville Cursive">Word</h1><!----inicio Word--->
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        Aula 1 - Introdução ao Processamento de Dados / Introdução ao Curso.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Introdução ao curso
                                        </li>
                                        <li>
                                            Introdução ao Processamento de dados
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Aula 2 - Introdução ao Sistema Operacional Windows
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Conhecendo o Windows.
                                        </li>
                                        <li>
                                            Ambiente de trabalho.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThree">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                        Aula 3 - Barra de Tarefas e Menu Iniciar
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Barra de tarefas.
                                        </li>
                                        <li>
                                            Menu Iniciar.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFor">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFor" aria-expanded="false" aria-controls="collapseFor">
                                        Aula 4 - Conhecendo o Teclado e Editores de Texto.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFor" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFor">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Usando o teclado.
                                        </li>
                                        <li>
                                            Notas Autoadesivas.
                                        </li>
                                        <li>
                                            Bloco de Notas.
                                        </li>
                                        <li>
                                            WordPad.
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFive">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                        Aula 5 -Calculadora, Paint e Ferramenta de Captura.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Usando o teclado.
                                        </li>
                                        <li>
                                            Calculadora.
                                        </li>
                                        <li>
                                            Paint.
                                        </li>
                                        <li>
                                            Ferramenta de Captura.
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSix">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                        Aula 6 - Continuação do Exercício da Aula 5.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Desenhos no Paint.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingSeven">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                                        Aula 7 - Pastas e Arquivos.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Trabalhando com arquivos e pastas.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingEight">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                                        Aula 8 - Exercícios de Fixação.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Exercitando  com arquivos e pastas.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingNine">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                                        Aula 9 - Armazenamento.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingNine">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Unidades de Medidas.
                                        </li>
                                        <li>
                                            Dispositivos de Armazenamento.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
                                        Aula 10 - Janelas.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Trabalhando com janelas
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingEleven">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
                                        Aula 11 - Arquivos.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEleven">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Manipulação de Arquivos.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwelve">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve" aria-expanded="false" aria-controls="collapseTwelve">
                                        Aula 12 - Painel de controle / Contas de usuário.
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwelve">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Contas de usuário.
                                        </li>
                                        <li>
                                            Sistema.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThirteen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThirteen" aria-expanded="false" aria-controls="collapseThirteen">
                                        Aula 13 - Tipos de Arquivos
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThirteen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Formatos de Arquivos e Programas para abri-los.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingFourteen">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFourteen" aria-expanded="false" aria-controls="collapseFourteen">
                                        Aula 14 - Prova
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFourteen">
                                <div class="panel-body">
                                    <ul>
                                        <li>
                                            Teste de Conhecimento.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--final do modulo de Word-->
                    </div><!----------------Final do grupo accordion--------------->
                </div>
            </div>
        </div><!--div.row-->
    </section>

<?=$this->render('bootstrap/footer',$data);?>