<?= $this->render('header'); ?>

    <div id="content">
        <div class="container-fluid">
            <div class="row">

                <aside id="sidebar" class="col-md-3">
                    <?= $this->render('aside'); ?>
                </aside><!--aside//-->

                <main id="conteudo" class="col-md-9">
                    <div class="main-content">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4>Usuários</h4>
                            </div>
                            <div class="panel-body save-item">
                                <h3><i class="glyphicon glyphicon-plus-sign"></i> Atualizar usuário</h3>
                                <hr>

                                <form class="form-horizontal" method="post">
                                    <div class="form-group">
                                        <label for="nome" class="col-sm-2 control-label">Nome</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" name="nome" id="nome" placeholder="Nome" value="<?=$data->nome?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="email" class="col-sm-2 control-label">Email</label>
                                        <div class="col-sm-10">
                                            <input type="email" class="form-control" name="email" id="email" placeholder="Email" value="<?=$data->email?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="senha" class="col-sm-2 control-label">Senha</label>
                                        <div class="col-sm-10">
                                            <input type="password" class="form-control" name="senha" id="senha" placeholder="Senha">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="senha2" class="col-sm-2 control-label">Repetir senha</label>
                                        <div class="col-sm-10">
                                            <input type="password" class="form-control" name="senha2" id="senha2" placeholder="Repetir senha">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="tipo" class="col-sm-2 control-label">Tipo</label>
                                        <div class="col-sm-10">
                                            <select name="tipo" id="tipo" class="form-control">
                                                <option value="1"<?=($data->tipo==1 ? ' selected' : '')?>>Administrador</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" name="status" value="1"<?=($data->status==1 ? ' checked' : '')?>> Ativo
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" class="btn btn-success">
                                                <i class="glyphicon glyphicon-save"></i>  Salvar
                                            </button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </main><!--//main-->

            </div>
        </div>
    </div><!--//#content-->


<?= $this->render('footer'); ?>