

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <footer>
                <p>Wellington leonardo -- © 20<?php echo date(y)?></p>
            </footer>
        </div>
    </div>    
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?=TPL.'bootstrap'?>/assets/js/bootstrap.min.js"></script>
<script src="<?=TPL.'bootstrap'?>/assets/js/jquery-3.1.1.min.js"></script>
</html>
<?php

