<?=$this->render('bootstrap/header',$data);?>
<?=$this->render('bootstrap/menu',$data);?>

<section class="container">
    <div class="row">
        <div class="col-sm-12">
            <header>
                <h2>
                    <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>
                    Sistema de controle Pedagogico do professor Wellington Leonardo
                </h2>
                <span>Escolha uma turma para ver o cronograma do curso</span>
            </header>
            <div class="col-xs-12 col-md-12">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->


                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="/app/Views/bootstrap/assets/images/montagememanutencao.jpg" alt="...">
                            <div>
                                <p class="alert-success" style="text-align: justify;  text-indent: 1.5em; padding: 3px">
                                    <strong>Montagem e Manutenção</strong> O objetivo do curso de Montagem e Manutenção
                                    de Micros PC é preparar profissionais como técnicos para Conserto, Manutenção, Configuração e Montagem de micro-computadores PC.
                                    O curso conta com um  modulo de redes capacitando os alunos a desenvolver e implantar projetos, configurar e gerenciar ambientes de redes para otimizar o funcionamento de uma empresa,
                                    seja ela de pequeno, médio ou grande porte, com qualidade e segurança nos processamentos da comunicação de dados necessários para sua operação.
                                </p>
                            </div>
                        </div>
                            <div class="item">
                                <a href="/opMicro">
                                    <img src="/app/Views/bootstrap/assets/images/operadorcomputador.jpg" alt="...">
                                </a>
                                <div>
                                    <p class="alert-success" style="text-align: justify;  text-indent: 1.5em; padding: 3px">
                                        <strong>Operador de Computador</strong>
                                        Ensinar ao aluno um conjunto de técnicas e conhecimentos que possibilitam o uso
                                        das principais ferramentas exigidas pelas empresas. Utilizando o sistema
                                        operacional Microsoft Windows como plataforma para ensinar a configurar e
                                        utilizar seus recursos. Também da Microsoft temos os Office que é a suíte de
                                        aplicativos mas pedidas para quem decidir trabalhar em um escritório.
                                    </p>
                                </div>
                            </div>
                            <div class="item">
                                <img src="/app/Views/bootstrap/assets/images/web2.jpg" alt="...">

                                <div>
                                    <p class="alert-success" style="text-align: justify;  text-indent: 1.5em; padding: 3px">
                                        <strong>Programaçao Web</strong> Curso pensado na carência de profissionais
                                        capazes de criar soluções que atendam às necessidades dos clientes.
                                        Antes de aprender as linguagens será apresentado ao aluno a lógica ensinando o aluno a pensar
                                        em soluções de problemas do mundo real com aplicações seguindo os padrões de Funcionalidade,
                                        Confiabilidade, Eficiência e no final trazendo aos clientes um  software fácil usar.
                                        Capacitando o aluno a criar páginas dinâmicas com HTML, CSS, PHP e conexão com o MYSQL.
                                    </p>
                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


        <section class="container">
            <div class="row">
                <div class="col-sm-12">
                    <header>
                        <h2><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Material de Apoio</h2>
                        <span>Seção à obtenção materiais adcionais para as aulas</span>
                    </header>

                        <div class="col-xs-12 col-md-4">
                            <figure>
                                <img src="/app/Views/bootstrap/assets/images/livros200x200.jpg" alt="..." class="img-thumbnail">
                                <figcaption style="color: #449D44"  >Tutoriais e Apostilas</figcaption>
                            </figure>
                        </div>
                        <div class="col-xs-12 col-md-4">
                            <figure>
                                <img src="/app/Views/bootstrap/assets/images/download.png" alt="..." class="img-thumbnail">
                                <figcaption style="color: #449D44">Download de Programas</figcaption>
                            </figure>
                        </div>
                        <div class="col-xs-12 col-md-4">
                            <figure>
                               <a href="/exercicios"> <img src="/app/Views/bootstrap/assets/images/exercicio.jpg" alt="..." class="img-thumbnail"></a>
                                <figcaption style="color: #449D44" >Lista de  Exercícios</figcaption>
                            </figure>
                        </div>
                </div>
            </div>
        </section>

<section class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <header>
                <h2><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Cadastre-se</h2>
                <span>Faça seu cadastro para ter acesso ao conteudo total do site</span>
            </header>
        </div>
    </div>
    <!-- Nesta seção temos o nome e o email -->
    <div class="form-horizontal">
        <div class="form-group" id="cadastro">
            <form>
                <div class="col-sm-4 col-md-3">
                    <label class="control-label" for="txtMensagem">Nome:</label>
                    <input type="text" id="txtNomeCompleto" class="form-control" placeholder="Preencha seu nome ">
                </div>

                <div class="col-sm-4 col-md-3">
                    <label class="control-label" for="txtMensagem">Email:</label>
                    <input type="email" class="form-control" id="txtEmail" placeholder="Preencha seu email">
                </div>
                <div class="col-sm-4 col-md-3">
                    <label class="control-label" for="txtMensagem">Senha:</label>
                    <input type="password" class="form-control" id="senha" placeholder="Digite uma senha">
                </div>
                <div class="col-sm-4 col-md-3">
                    <label class="control-label" for="txtMensagem">Digite a senha novamente:</label>
                    <input type="password" class="form-control" id="confsenha" placeholder="Confirme a senha digitada">
                    <br>
                    <button id="btnEnvia" class="btn btn-success">Cadastra-se</button>
                </div>
            </form>
        </div>
    </div>
    </div>
</section>
</section>
<section class="container">
    <div class="row">
        <div class="col-sm-12">
            <header>
                <h2><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Comentários</h2>
                <span>Nessa seção, escreva dados adicionais que ache importante</span>
            </header>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <p>
                Se você tem mais algum comentário ou dúvidas, escreva no campo a seguir.</p>
        </div>
        <div class="col-md-8">
            <form>
                <div class="form-group">
                    <label class="control-label" for="txtMensagem">Sua mensagem</label>
                    <textarea class="form-control" rows="6" id="txtMensagem"></textarea>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-md-offset-8">
            <button id="btnEnvia" class="btn btn-success">
                Enviar Mensagem
            </button>
        </div>
    </div>
</section>
<?=$this->render('bootstrap/footer',$data);?>

