<div class="clearfix"></div>

<footer class="section">
    <hr>
    <div class="container-fluid">
        <div class="text-center"><span>Copiryght 2016 - Todos os direitos reservados</span></div>
    </div>
</footer>
<script type="text/javascript" src="/app/views/<?= TPL_ADM ?>/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="/app/views/<?= TPL_ADM ?>/assets/js/bootstrap.min.js"></script>
</body>
</html>