<?=$this->render('header');?>

<div id="content">
    <div class="container-fluid">
        <div class="row">

            <aside id="sidebar" class="col-md-3">
                <?=$this->render('aside');?>
            </aside><!--aside//-->

            <main id="conteudo" class="col-md-9">
                <div class="main-content">
                    <h1>Conteudo</h1>
                </div>
            </main><!--//main-->

        </div>
    </div>
</div><!--//#content-->


<?=$this->render('footer');?>